; Memuat ekstensi FFI
extension_dir = "C:/php-8.0.30/ext"
extension=ffi

; Mengaktifkan fitur FFI
; true = aktif untuk semua (Web & CLI)
; cli  = hanya aktif jika dijalankan lewat terminal
ffi.enable=true

; Opsional: Menampilkan error agar mudah debug jika DLL gagal di-load
display_errors=On
display_startup_errors=On
error_reporting=E_ALL